### ISSUE TITLE
退出virtualenv的时候直接退出terminal，而不是virtualenv环境变量

### ISSUE THREAD

**Issue by xavierzhao** [martyr-deepin/deepin-terminal#32]
如：
workon test
exit

**Comment by manateelazycat** [comment]
您好， 你先看一下其他终端是否有相同的问题来排除一下深度终端的问题， 深度终端的实现都是和其他终端标准是一致的。

如果是深度终端的问题， 请写一下详细的重现步骤， 以方便我进一步测试， 谢谢您的报告！

**Comment by xavierzhao** [comment]
标准终端没这个问题.
1. 安装virtualenv
2. 安装virtualenvwrapper
3. mkvirtualenv test
4. workon test
5. exit

**Comment by manateelazycat** [comment]
virtualenv 要怎么安装， 我只装了 virtualenvwrapper, 没法继续执行．

建议您在终端中先开一个新的终端， 然后在新的终端中运行上面的命令， 如果终端退出后，把第一个终端的报错信息粘贴给我看一下， 这样比较容易快速定位问题．

2014-05-09 16:56 GMT+08:00 xavierzhao notifications@github.com:

**Comment by xavierzhao** [comment]
如果你已经装了virtualenvwrapper，那就不用装virtualenv了，因为virtualenvwrapper实质上是在virtualenv上包裹了一层

直接执行第三步吧

**Comment by manateelazycat** [comment]
我的输出是：
andy@andy-pc:mkvirtualenv test
New python executable in test/bin/python
Installing setuptools, pip...done.
(test)andy@andy-pc:~$ workon test
(test)andy@andy-pc:~$

貌似没有成功， 您的是 Deepin 2013 吗？ 我测试的是 Deepin 2014 最新测试版

2014-05-09 17:21 GMT+08:00 xavierzhao notifications@github.com:

**Comment by xavierzhao** [comment]
我也是2014测试版，你执行exit后，是否直接退出终端了？如果是那就有问题

**Comment by manateelazycat** [comment]
exit 是退了， 但是 3 和 4 步骤并没有像 shell 进入啊， 那又何来退出？

2014-05-09 17:55 GMT+08:00 xavierzhao notifications@github.com:

**Comment by xavierzhao** [comment]
如果你有其他终端程序，可以试下，其他终端的表现如下：
1. (test)andy@andy-pc:~$ exit
2.  andy@andy-pc:~$ exit (如果再次exit)
3. 退出终端

**Comment by manateelazycat** [comment]
我试了一下 gnome-terminal 和 terminator 都是直接退出的， 抱歉无法重现您的问题， 先关闭。
如果依然有问题， 欢迎重新打开任务讨论。
