### ISSUE TITLE
Error when executing deepin-terminal

### ISSUE THREAD

**Issue by ghost** [martyr-deepin/deepin-terminal#36]
When I attempt to run deepin from the terminal I get the following error:

Xlib.protocol.request.QueryExtension
Traceback (most recent call last):
  File "/usr/bin/deepin-terminal", line 4017, in <module>
    Terminal(opts.quake_mode, opts.working_directory, opts.startup_command).run()
  File "/usr/bin/deepin-terminal", line 401, in **init**
    always_at_center=not terminal_has_running
TypeError: **init**() got an unexpected keyword argument 'always_at_center'

I don't know what this means. Could I be missing something Python-related? A lot of packages installed with this, so I assumed I had everything. I am running Peppermint Linux 3, which is similar to Lubuntu 12.04.

**Comment by ghost** [comment]
Updated to the newest version today (4/18/14, didn't notice the version number) and the previous error is gone, replaced by this one: 

Xlib.protocol.request.QueryExtension
Traceback (most recent call last):
  File "/usr/bin/deepin-terminal", line 2955, in <module>
    Terminal(quake_mode).run()
  File "/usr/bin/deepin-terminal", line 356, in **init**
    self.general_settings = GeneralSettings()
  File "/usr/bin/deepin-terminal", line 2159, in **init**
    font_widget.set_select_index(font_families.index(font))
ValueError: '\xe6\x96\x87\xe6\xb3\x89\xe9\xa9\xbf\xe7\xad\x89\xe5\xae\xbd\xe5\xbe\xae\xe7\xb1\xb3\xe9\xbb\x91' is not in list

**Comment by manateelazycat** [comment]
Have fixed it.
