### ISSUE TITLE
Stuck state when search is initiated Mint 16

### ISSUE THREAD

**Issue by rhomnousia** [martyr-deepin/deepin-terminal#39]
On Linux Mint 16
1. Ctrl - ' : Pops search overlay up.
2. You can type into the search field
3a. The up arrow, down arrow, and exit button will not function
3b. The terminal becomes unresponsive and the process must be killed

Unfortunately I haven't touched python in years or i'd debug this, great terminal though!

**Comment by mingchuno** [comment]
I got the same problem too on Linux Mint 17

**Comment by ihrwein** [comment]
:+1:

**Comment by ihrwein** [comment]
IMHO the problem is, that the `python-vt` package doesn't export every functions defined by GNOME's VTE terminal. One of them is the `search_set_gregex()` function. I checked the trusty version.

I think they use this version of `python-vte`: https://github.com/linuxdeepin/python-vte

**Comment by manateelazycat** [comment]
deepin terminal 2.0 will use offical vte instead python-vte, thanks for report!
