### ISSUE TITLE
功能请求：希望有个“总是最前” 的功能，类似  Terminator 终端。

### ISSUE THREAD

**Issue by zhuomingliang** [martyr-deepin/deepin-terminal#43]
Hello，

希望有个“总是最前” 的功能，类似  Terminator 终端。

**Comment by manateelazycat** [comment]
这个功能是由窗口管理器来提供， 目前已经在 Deepin 15.2 中实现， 请更新到最新版系统后， 按 Alt + Space 来调出这个窗口

**Comment by zhuomingliang** [comment]
好的，非常感谢。
