### ISSUE TITLE
error when calling deepin-terminal -e

### ISSUE THREAD

**Issue by oberon-manjaro** [martyr-deepin/deepin-terminal#48]
When I try to launch `$ deepin-terminal -e sudo setup` the terminal opens briefly, then crashes.

```
Xlib.protocol.request.QueryExtension
TerminalWrapper.get_working_directory got error: [Errno 2] No such file or directory: '/proc/1577/cwd'
```

When I run `sudo deepin-terminal -e setup` it works.

**Comment by manateelazycat** [comment]
deepin terminal 2.0 has fixed those problem, thansk for your report!
