### ISSUE TITLE
Feature request: scroll bar option in terminal

### ISSUE THREAD

**Issue by edencorbin** [martyr-deepin/deepin-terminal#51]
I would love to see an option to turn a scroll bar on in the deepin terminal. I understand that perhaps the majority would not need, and it may not fit the design (which is my favourite of any OS), and having it turned off by default might make sense. However, it is a very efficient and useful way to search through large amounts of console output, and I, for one, would turn it back on for usability.

**Comment by edencorbin** [comment]
bump bump, any interest in this idea, a scroll bar would be so useful.

**Comment by manateelazycat** [comment]
This feature has fix in deepin terminal 2.0 (still in developing)

Thanks for report!
