### ISSUE TITLE
Gentoo installation 

### ISSUE THREAD

**Issue by firearasi** [martyr-deepin/deepin-terminal#52]
Any instruction on how to install deepin-terminal on gentoo?

**Comment by fasheng** [comment]
I'm not similar with gentoo, but here are PKGBUILDs from Arch Linux, hope it helps:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/deepin-terminal
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-deepin-ui
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-deepin-vte

By the way, we could discuss such package porting details in https://github.com/linuxdeepin/developer-center/issues
:smile:
