### ISSUE TITLE
Add ligatures font support 

### ISSUE THREAD

**Issue by 7sDream** [martyr-deepin/deepin-terminal#53]
I'm using [FiraCode](https://github.com/tonsky/FiraCode) font in deepin-terminal. It's beautiful, but font ligatures is not supported.

There are some terminal support ligatures like Black Screen, Butterfly, QTerminal etc. And also many are not support, like gnome-terminal, iTerm 2, Terminator. (From [FiraCode Terminal Support Table](https://github.com/tonsky/FiraCode#terminal-support)).

This is a great feature which will make deepin-terminal stand out.

QTermianl vs deepin-terminal:

![](http://ww3.sinaimg.cn/large/88e401f0jw1f81alojrb5j210i0fhn1u.jpg)

**Comment by manateelazycat** [comment]
Thanks for suggestion, vte widget can't implement that feature, sorry.
