### ISSUE TITLE
Import/Export remotes

### ISSUE THREAD

**Issue by emulienfou** [martyr-deepin/deepin-terminal#55]
Is it possible to add a new feature to import/export all remotes(such as a sql file by example)?

It will be very useful when using more than 1 computer with Deepin or if re-installation is needed.

**Comment by manateelazycat** [comment]
Yes, please copy deepin-terminal config file: ~/.config/deepin/deepin-terminal/server-config.conf

**Comment by emulienfou** [comment]
@manateelazycat thanks for your answer, however is it possible to save the passwords related to each server ?

**Comment by manateelazycat** [comment]
@emulienfou deepin-terminal save password in your session keyring, and not plain text, for password safely.

You can try save/restore keyring, it perhaps help. ;)
