### ISSUE TITLE
快捷键打开终端无法输入中文

### ISSUE THREAD

**Issue by listenerri** [martyr-deepin/deepin-terminal#56]
> 系统：archlinux
> 桌面：dde
> 使用startx的方式启动X，配置文件为：～/.xinitrc

当使用快捷键打开深度终端（包括雷神模式）时，会丢失一些环境变量，包括fcitx输入法框架所需要一些变量，从而导致无法输入中文，比如：

```
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
//上述几个变量配置在.xinitrc文件中
```

当用鼠标从dock点击打开深度终端时，看起来一切正常，上个图对比下，
左边是快捷键打开的终端，右边是鼠标从dock点击打开的终端：
![20161011131528](https://cloud.githubusercontent.com/assets/7995379/19259568/85655dda-8fb5-11e6-9a28-bd9743a8c265.png)

**Comment by listenerri** [comment]
好像时昨晚更新了下deepin-wm后出现的问题，具体是不是这个原因就不知道了，之前是否有这个问题没有留意

**Comment by listenerri** [comment]
又试了下，好像不只是用快捷键打开会出现这个问题，而且不只是深度终端会不能输入中文

**Comment by manateelazycat** [comment]
不能输入中文一般是输入法配置有问题，　这个是系统问题。
终端如果不能输入中文我会第一时间知道的。　;)

**Comment by listenerri** [comment]
@manateelazycat 可是同样的配置，切换到i3wm就正常

**Comment by listenerri** [comment]
@manateelazycat 
dde还是有这个问题, 下面是我home目录下的的.xinitrc文件,
fcitx相关的变量在这个文件里设置的:
[xinitrc.txt](https://github.com/linuxdeepin/deepin-terminal/files/670936/xinitrc.txt)

这个是使用快捷键打开终端后, 使用命令'env > filename.txt'得到的文件:
[open-key-env.txt](https://github.com/linuxdeepin/deepin-terminal/files/670940/open-key-env.txt)

这个是用鼠标在dock上点击打开终端后, 使用命令'env > filename.txt'得到的文件:
[open-dock-env.txt](https://github.com/linuxdeepin/deepin-terminal/files/670942/open-dock-env.txt)

**Comment by listenerri** [comment]
@manateelazycat 
将fcitx相关的变量放到`/etc/environment`文件里就正常了, 
用快捷键打开终端以及文件管理器都可以输入中文了
