### ISSUE TITLE
[request] save last opend tabs

### ISSUE THREAD

**Issue by breadlesscode** [martyr-deepin/deepin-terminal#57]
Hi guys,

can you add an option to save last opened tabs? That would be awesome =)

**Comment by manateelazycat** [comment]
Because terminal tab not just contain local terminal.
Terminal need re-execute command if has command is running when close terminal.

From security point, terminal shouldn't execute command automatically, perhaps i won't add this feature, sorry.

Anyway, thanks for your suggestion!
