### ISSUE TITLE
Please add bookmarks

### ISSUE THREAD

**Issue by bigbruno** [martyr-deepin/deepin-terminal#58]
One good point in Konsole is bookmarks, add this function in Deepin Terminal make this the better option.

**Comment by manateelazycat** [comment]
Do you try "command manage" in deepin-terminal 2.1 ?

Command manage feature can add command in right slide to execute when you next click or press keystroke.

**Comment by bigbruno** [comment]
You are right, after update this feature are add, really thanks.

Maybe in future add option for "Command Manage" Feature mantained open in Deepin Terminal.

Like one checkbox in bottom for maintain opened.
