### ISSUE TITLE
[Feature Request] auto-close feature in dropdown-terminal

### ISSUE THREAD

**Issue by ceyhunn** [martyr-deepin/deepin-terminal#59]
When  deepin-terminal is  opened  like  dropdown-terminal and loses the focus, it would be nice to add auto-close feature. Not quit  the terminal , just running in background...

Thanks for your hard work!!!

**Comment by manateelazycat** [comment]
In most cases, the terminal needs to be combined with the browser, such as side copy the browser edge of the text in the terminal code test.

If you click on the blank automatically hide the terminal, will lead to back and forth when switching is not convenient.

Terminal in the PC environment or to assist with other software features, it is not just like the terminal in the game as a subsidiary role.

So this proposal can not be accepted, thank you for your suggestion.

**Comment by ceyhunn** [comment]
I got it, but most popular dropdown terminals like guake, yakuake have this feature, it is just a option,   I like your work  very much, because your  deepin desktop, deepin applications  designed more elegant, more obviously viewed than others.  I use this feature for many years. If you add this feature, it will be very pleasant for me...

Best Regards,
Jeyhun
