### ISSUE TITLE
SIGSEGV when charger connected

### ISSUE THREAD

**Issue by shreyanshk** [martyr-deepin/deepin-terminal#62]
Hello,
I get SIGSEGV error when I connect laptop charger to laptop.

error:
[ 4137.575858] deepin-terminal[7125]: segfault at 0 ip 0000000000461336 sp 00007ffd1a450490 error 4 in deepin-terminal[400000+94000]

OS : Arch Linux, completely up-to-date, latest version.

Please help!

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/deepin-terminal/issues/62
