### ISSUE TITLE
ssh_login.sh 在用户用本地有公私钥的时候， expect 用密码登陆会失效。

### ISSUE THREAD

**Issue by manateelazycat** [martyr-deepin/deepin-terminal#7]

**Comment by fasheng** [comment]
之前学过一些 tcl，有时间会尝试解决该 issue。

**Comment by manateelazycat** [comment]
期待！ :)

**Comment by fasheng** [comment]
看了代码，感觉有两种解决思路：
1. 给 `ssh_login.sh` 新增 `SSH_PROMPT` 变量，使 expect 能够识别`PS1`中的关键字从而判断是否成功登录，通常为`"(%|#|\\$) ?”`），但并不保证通用，所以还需要给用户留出设置该变量的接口。
2. 通过 `password` 来判断，若用户没有设置密码，则认为不需要进行 `expect` 操作，若登录过程中需要输入密码，则由用户自己处理，若不需要输入密码，则将成功登录。与之前相比唯一的区别是，若用户没有设置密码，第一次登录时的 `yes/no` 必须要手动处理。此外，将 `password` 作为可选项还有安全方面的考虑，否则通过命令 `ps -u | grep expect` 即可看到用户的明文密码。

所以我倾向于第二种解决方法，不知您怎么看？

**Comment by nohappiness** [comment]
当时我的思路是和你的第二种一样的，主要是对expect的坑爹语法表示无力，不知道如何下手丫

**Comment by fasheng** [comment]
代码已经完成，不过目前主分支运行报错 `TypeError: __init__() got an unexpected keyword argument 'destroy_func'`，等主分支稳定后再提交代码

**Comment by manateelazycat** [comment]
更新一下 deepin-ui 就可以了， deepin-ui application destroy_func 的更新主要解决关闭按钮的时候提醒用户有活动的进程， 防止用户会因为错误关闭而损失数据。

**Comment by manateelazycat** [comment]
https://github.com/linuxdeepin/deepin-ui 同步下来以后 ./repos.sh install 就可以了， 然后 pull request 我来合并吧
